# Generated by Django 4.0.1 on 2022-02-12 14:49

from django.db import migrations, models
import uuid
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resumes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('template_name', models.CharField(max_length=32)),
                ('demo_image', versatileimagefield.fields.VersatileImageField(upload_to='resume-demos')),
                ('paid', models.BooleanField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
