# Generated by Django 4.0.1 on 2022-03-05 17:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('author', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=256)),
                ('content', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
